# Makefile

# Define the command to be the default goal (when you just type 'make').
.DEFAULT_GOAL := run

# 'run' target for starting the streamlit application.
run:
	@echo "Running Streamlit app..."
	streamlit run Home.py

# Add more targets as needed
